[package]
name = "deployd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"]}
futures = "0.3"

bollard = "0.16"
